sudo: required
language: python
python:
  - "3.4"
  - "3.6"

install:
  # Install build tools and ack-grep for checks
  - sudo apt install devscripts dh-make ack-grep -y

script:
  # Build the binary (.deb)
  - debuild -i -us -uc -b
  # Install the binary, also fireing the debian scripts
  - sudo apt install ../*.deb -y
  # Check if the username passthough works correctly with sudo
  - 'howdy | ack-grep --passthru --color "current active user: travis"'
  - 'sudo howdy | ack-grep --passthru --color "current active user: travis"'
  # Remove howdy from the installation
  - sudo apt purge howdy -y

notifications:
  email:
    on_success: never
    on_failure: always

addons:
  apt:
    update: true
