language: python
sudo: required

install:
  - sudo apt install devscripts dh-make -y

script:
 - debuild -i -us -uc -b
 - sudo apt install ../*.deb -y
 - sudo howdy help
 - sudo howdy list
 - sudo apt purge howdy -y

notifications:
  email:
    on_success: never
    on_failure: always
